networks:
  quiz:
    driver: bridge
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    networks:
      - quiz
    volumes:
      - mongo_data:/data/db
  auth-api:
    build: ./auth
    ports:
      - 3000:3000
    networks:
      - quiz
    volumes:
      - auth_data:/app/data
  quiz-api:
    build: ./quiz
    ports:
      - 4000:4000
    environment:
      AUTHAPIPORT: 3000
      USERAPIURL: http://user-api:5000/user
      AUTHAPIURL: http://auth-api:3000/auth
      MONGO_URI: mongodb://mongo/quiz
    networks:
      - quiz
    volumes:
      - quiz_data:/app/data
    depends_on:
      - mongo
      - auth-api
      - user-api
  user-api:
    build: ./user
    ports:
      - 5000:5000
    environment:
      AUTHAPIURL: http://auth-api:3000/auth
      MONGO_URI: mongodb://mongo/users
    networks:
      - quiz
    volumes:
      - user_data:/app/data
    depends_on:
      - mongo
      - auth-api
volumes:
  mongo_data:
  auth_data:
  quiz_data:
  user_data: